- name:  installing python
  ansible.builtin.import_role:
    name: common
    tasks_from: installing-python
- name: creating user and app directory
  ansible.builtin.import_role:
    name: common
    tasks_from: setup-app
- name: installing dependencies
  ansible.builtin.shell: pip3.11 install -r requirements.txt
  args:
    chdir: /app   
- name: copying user.service and starting and enabling, deamon reload
  ansible.builtin.import_role:
    name: common
    tasks_from: systemdsetup     
