- name: congiguring rabbitmq
  ansible.builtin.shell: "{{item}}"
  loop:
    - curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
    - curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
- name: installing rabbitmq
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed 
- name: starting and enabling rabbitmq
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes     
- name: creating rabbitq user and password
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

