- name: installing nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: installing-nodejs
- name: setting up app directory
  ansible.builtin.import_role:
    name: common
    tasks_from: setup-app  
- name: installing dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app
- name: deamon reload
  ansible.builtin.import_role:
    name: common
    tasks_from: systemdsetup
- name: setting up mongodb
  ansible.builtin.import_role:
    name: common
    tasks_from: setting-mongo
- name: loading schema
  ansible.builtin.import_role:
    name: common
    tasks_from: loadingschemamongodb 


